name: CI
on: [push]
jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
    - name: Install dependencies
      run: |
          apt-get update &&  apt-get install -y libayatana-appindicator3-dev tzdata nodejs npm 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Run golangci-lint
      run: golangci-lint run ./...
